# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: f75f21a
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: gunns-sims
include_funding: true
override: true
override_codecov: false
override_coveragerc: false
override_env: false
override_flake8: false
override_gitattributes: false
override_gitignore: true
override_isort: false
override_precommit: false
override_pyrightconfig: false
override_pytest: false
override_sourcery: false
override_update: false
override_vscode_extensions: false
override_vscode_launch: false
override_vscode_settings: false
override_vscode_tasks: false
project_email: blake.naccarato+gunns-sims@gmail.com
project_name: gunns-sims
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: "3.10"
use_dvc: false
year_of_project_creation: 2022
